project_id = "eypbkwmmoitaprtinpjg"

[functions.parse-google-sheet]
verify_jwt = true

[functions.parse-leads-sheet]
verify_jwt = true

[functions.notion-crm-sync]
verify_jwt = true

[functions.parse-proposal-cart]
verify_jwt = true

[functions.banco-inter]
verify_jwt = true

[functions.nfse-sp]
verify_jwt = true

[functions.write-google-sheet]
verify_jwt = true

[functions.parse-bank-statement]
verify_jwt = true

[functions.ai-report]
verify_jwt = false

[functions.ai-write]
verify_jwt = false

[functions.audit-just-travel]
verify_jwt = true
